# Generated by Django 4.2.4 on 2023-08-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('credits', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
